server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: DEBUG

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file-service/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer-service/**