server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: servicio-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: servicio-cliente
          uri: lb://servicio-cliente
          predicates:
            - Path=/cliente/**
        - id: servicio-foto
          uri: lb://servicio-foto
          predicates:
            - Path=/foto/**